name: Celler
main: dk.setups.celle.CellePlugin
author: AbdisKiosk
version: '${version}'
api-version: '26.2'
website: https://www.setups.dk
depend: [WorldGuard, WorldEdit, Vault]
softdepend: [PlaceholderAPI]
permissions:
  cell.command.unrent:
    description: Allows you to end your cell rental
    default: true
  cell.command.unrent.other:
    description: Allows you to end other players' cell rentals
    default: op
  cell.command.member.add:
    description: Allows you to add members to your cell
    default: true
  cell.command.member.add.other:
    description: Allows you to add members to other players' cells
    default: op
  cell.command.member.remove:
    description: Allows you to remove members from your cell
    default: true
  cell.command.member.remove.other:
    description: Allows you to remove members from other players' cells
    default: op
  cell.command.info:
    description: Allows you to view information about your cell
    default: true
  cell.command.info.other:
    description: Allows you to view information about other players' cells
    default: true
  cell.command.list:
    description: Allows you to list your cells
    default: true
  cell.command.list.other:
    description: Allows you to list other players' cells
    default: true
  cell.command.teleport:
    description: Allows you to teleport to your cell
    default: op
  cell.command.teleport.other:
    description: Allows you to teleport to other players' cells
    default: op
  cell.admin:
    description: Allows you to use administrator commands
    default: op
  cell.admin.migrate:
    description: Allows you to import Staxi cells
    default: op


